### ISSUE TITLE
Mehrere Tags pro Kachel ermöglichen

### ISSUE THREAD

**Issue by Michael-Schaer** [scout-ch/Portal#3]
Diese Idee kommt aus der Ausbildung und Betreuung.

Es sollen mehrere Tags pro Kachel zugeordnet werden können. Dadurch können z.B. Ausbildungsangebote sowohl in der Kategorie für die Ausbildung, wie auch in der für einen spezifischen Bundeskurs erscheinen. Beide Kategorien sollen also verlinkt werden können und teilweise die gleichen Kacheln enthalten.

**Comment by Michael-Schaer** [comment]
Alternative: Einen Link auf die definierte Standardansicht der Gruppe ermöglichen. So können Kacheln aus verschiedenen Gruppen der Standardansicht angefügt und via Link angezeigt werden.

**Comment by jsqnp** [comment]
Mehrere Kategorien pro Kachel lösen diese Anforderung nicht. Die Kacheln können jeweils nur vom Inhaber bearbeitet werden.
Die Alternative Lösung wird in #4 behandelt.
